config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  root to: 'chatrooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  #association
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # association
  has_many :message
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :config_permitted_parameters, if: :devise_controller?

  protected

  def config_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys:[:username])
  end

end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom
  end

  def destroy
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
    redirect_to chatrooms_path
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :require_logged_in
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(30).reverse
    @chatroom_user = ChatroomUser.where(user_id: current_user.id, chatroom: @chatroom).first
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = current_user.chatrooms.new(chatroom_params)
    respond_to do |format|
      if current_user.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end

    def require_logged_in
      redirect_to new_user_session_path if current_user.nil?
    end
end

app/controllers/messages_controller.rb
class MessagesController  < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom
  #def create
    #byebug
    #message = @chatroom.messages.new(message_params)
    #message.user = current_user
    #message.save
    #MessageRelayJob.perform_later(message)
    #respond_to do |format|
      #format.js
    #end
  #end

  def destroy

  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def message_params
    params.require(:message).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Join', chatroom_chatroom_users_path(chatroom), method: :post %></td>
        <td><%= link_to 'Leave', chatroom_chatroom_users_path(chatroom), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<% printed_unread_line = false %>
<%#<marquee behavior="scroll" direction="right">%>
<h5 class="title-conversation"><strong><%= @chatroom.name %></strong></h5>
<%#</marquee>%>
<div data-behavior="messages" data-chatroom_id="<%= @chatroom.id %>" class="messages">
  <% @messages.each do |message| %>
    <% if !printed_unread_line && (message.created_at > @chatroom_user.last_read_at) %>
      <% printed_unread_line = true %>
      <div class="strike">
        <span>Unread messages</span>
      </div>
    <% end %>
    <%= render message %>
  <% end %>
</div>


<%= form_with model: [@chatroom, Message.new], id: "new_message", remote: true, format: :js do |f| %>
  <%= f.text_area :body, rows: 2, class: "form-control", autofocus: true, placeholder: "Enter for send message" %>
<% end %>

app/views/layouts/_conversation.html.erb
<div class="col-sm-8 main-conversation">
  <%= yield %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-fixed-top navbar-light nav-fill w-100" id="top-navbar">
  <a class="navbar-brand" id="logo" href="<%= root_path %>">Xlack</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= edit_user_registration_path %>">Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <a class="nav-link" href="<%= user_session_path %>">Sign in</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_leftbar.html.erb
<div class="col-sm-2 leftbar">
  <% if user_signed_in? %>
    <h5 class="title-leftbar"><strong>Chatrooms</strong></h5>
    <ul class="list-room">
      <% current_user.chatrooms.each do |chatroom| %>
        <li><%= link_to chatroom.name, chatroom, data: { behavior: "chatroom-link", chatroom_id: chatroom.id } %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneOfSlack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>%>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/header' %>
      </div>
    </div>
    <div class="container-fluid main-container">
      <div class="row">
        <%= render 'layouts/leftbar' %>
        <%= render 'layouts/conversation' %>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div>
  <strong><%= message.user.username %></strong>
  : <%= message.body %>
</div>

app/views/messages/create.js.erb
$("#new_message")[0].reset();